### ISSUE TITLE
the standard output  gives an error

### ISSUE THREAD

**Issue by xdli009** [d-j-e/SNPPar#10]
**Hello, 
When I run the program, the standard output  gives an error:**
--- alignment including ancestral nodes saved as  
	 treetime_out/ancestral_sequences.fasta

--- tree saved in nexus format as  
	 treetime_out/annotated_tree.nexus

Extracting mutation events from ASR results...
Traceback (most recent call last):
  File "/mnt/data/home/lxd/miniconda3/bin/snppar", line 8, in <module>
    sys.exit(main())
  File "/mnt/data/home/lxd/miniconda3/bin/snppar.py", line 2646, in main
    snps_mapped, mapped_node_sequences, node_names_mapped = mapSNPsTT(snps_to_map,snptable,strains,arguments.tree,directory,tree,prefix,log)
  File "/mnt/data/home/lxd/miniconda3/bin/snppar.py", line 1324, in mapSNPsTT
    snps_mapped = readMappedSNPs(output_dir+'annotated_tree.nexus',tree,snps_to_map,snptable)
  File "/mnt/data/home/lxd/miniconda3/bin/snppar.py", line 2522, in readMappedSNPs
    derived_node = the_tree.search_nodes(name=parts[0])[0]
IndexError: list index out of range

**Command Input:**
`snppar -m snps.fa -l ex_snp_pos.txt -t snps_filter_midpoint.nwk -g genome.gbk`

**Thanks a lot, hope to get your suggestions!**

**Comment by d-j-e** [comment]
First of all, apologies for not replying sooner - I'm not (yet) getting emails when issues are posted so hadn't notice yours and another issue...

Is there any possibility you could send me the files you are using? I have one idea... (possibly a rogue character in an isolate name????)

**Comment by d-j-e** [comment]
Just released new version and did a run with the test data - can you try the same test data? (available in the git in the folder `test_data`)

**Comment by scwatts** [comment]
Closing due to inactivity, please reopen if you find this error is present in the latest version.
