### ISSUE TITLE
log string message vs log function :: name conflcit

### ISSUE THREAD

**Issue by EricDeveaud** [d-j-e/SNPPar#11]
hello

after installing SNPPar-0.4dev  
and  running some functionale test eg
```
snppar.py -s ../../datas/SNPPar/MTB_Global_L2_alleles.csv -t ../../datas/SNPPar/MTB_Global_L2.tre -g ../../datas/SNPPar/NC_00962_3_1.gbk -d /local/gensoft2/tests/SNPPar/0.4dev -f
```

I got this error.

```
Traceback (most recent call last):
  File "/local/gensoft2/exe/SNPPar/0.4dev/bin/snppar.py", line 2663, in <module>
    main()
  File "/local/gensoft2/exe/SNPPar/0.4dev/bin/snppar.py", line 2644, in main
    snps_mapped, tree_with_nodes, mapped_node_sequences, node_names_mapped = mapSNPs(arguments.fastml_execute, snps_to_map, snptable, strains, arguments.tree, directory,log)
  File "/local/gensoft2/exe/SNPPar/0.4dev/bin/snppar.py", line 1296, in mapSNPs
    executeCommand(fastml_command, log)
  File "/local/gensoft2/exe/SNPPar/0.4dev/bin/snppar.py", line 89, in executeCommand
    log(log, message, "CRITICAL")
TypeError: 'str' object is not callable
```

It seems that is due to name conflict between loag (function) and log (str holding the mesage)

fix is quite easy: 

```
--- snppar.py.ori	2020-04-12 18:00:41.860354451 +0000
+++ snppar.py	2020-04-12 17:52:09.550799346 +0000
@@ -86,9 +86,9 @@
 		message = 'Failed to run command: ' + command
 		logPrint(log, message, "CRITICAL")
 		message = 'stdout: ' + result.stdout
-		log(log, message, "CRITICAL")
+		logPrint(log, message, "CRITICAL")
 		message = 'stderr: ' + result.stderr
-		log(log, message, "CRITICAL")
+		logPrint(log, message, "CRITICAL")
 		sys.exit(1)
 	else:
 		message = 'stdout: ' + result.stdout
```

and log function may be removed

**Comment by d-j-e** [comment]
Hi Eric,

thank you for submitting the error. 

Can confirm said same error (during FastML test runs for the paper) and a fix has already been applied to version 0.4.1dev, which I will release in the coming days.

Please, if you find anymore, do please let me know
.
And apologies for not replying earlier - for some reason, I don't (yet) get emails when an issue is posted so had not noticed this and one other...

regards,
David
